### ISSUE TITLE
Negative Dimension Size 

### ISSUE THREAD

**Issue by karanchawla** [kwotsin/transfer_learning_tutorial#10]
Hey so I successfully created the tfrecords dataset and my dataset consists of 80 x 80 x 3 size images and 2 classes. I also edited the `train_flowers.py` to reflect the aforementioned changes i.e. change the variable `image_size = 80` and `num_classes = 2`. 

When I run the code, I get  the following error: 
```
I completed dataset information.
Successfully split the dataset
Successfully loaded the batchset
Traceback (most recent call last):
  File "train_flowers.py", line 300, in <module>
    run()
  File "train_flowers.py", line 195, in run
    logits, end_points = inception_resnet_v2(images, num_classes = dataset.num_classes, is_training = True)
  File "/path/to/inception_resnet_v2.py", line 197, in inception_resnet_v2
    scope='Conv2d_1a_3x3')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 131, in avg_pool2d
    outputs = layer.apply(inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 492, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 441, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/pooling.py", line 276, in call
    data_format=utils.convert_data_format(self.data_format, 4))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1741, in avg_pool
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 48, in _avg_pool
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 5 from 3 for 'InceptionResnetV2/AuxLogits/Conv2d_1a_3x3/AvgPool' (op: 'AvgPool') with input shapes: [?,3,3,1088].
```

It looks like a dimension issue, but can't figure out where its creeping in from. Have you experienced this before? 

Karan

**Comment by kwotsin** [comment]
The issue comes from your image size being too small. Average pooling has a certain kernel size (which is 5x5 in this case), but because your image size is too small (80 vs the original 299), when the input feature map reaches the average pooling layer, its height and width are too small for the average pooling kernel. This is what the error means by a potential negative dimension created because of subtracting 5 (avgpool kernel size) from 3 (your input feature map size).

Solution: Perhaps you can try using a larger image size? From what I know, inception models require some modifications to smaller image size. You can also try other architectures like mobilenet or resnet which are less susceptible to this issue.

**Comment by karanchawla** [comment]
Hey, thanks for the quick response. Yes, after digging a little deeper, I tracked the error down and reduced the kernel size from the default 5 to 3. That seems to work and gives me an auc of about 93%

Thanks. I'll close this issue now.

**Comment by michirup** [comment]
@karanchawla Hi! Can I ask you how you managed to change the kernel size using the code by @kwotsin .

Michela
